language: c
os: osx

before_install:
  - wget https://github.com/chrmoritz/starcheat/releases/download/4f7bd31/local_cache.tar.gz
  - unset PYTHONPATH

install:
  - sudo tar xf local_cache.tar.gz -C /usr

script:
  - mac/travis.rb

branches:
  only:
    - /^v?\d+(\.\d+)*$/

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/starcheat-$TRAVIS_BRANCH-osx.tar.gz
  on:
    tags: true
